export const CONTENTS_WORKER_START = 'CONTENTS_WORKER_START'
export const GET_ASC_CONTENTS = "GET_ASC_CONTENTS"
export const GET_DESC_CONTENTS = "GET_ASC_CONTENTS"
export const GET_NEXT_CONTENTS = "GET_NEXT_CONTENTS"

export const TO_ASC_MODE = "TO_ASC_MODE"
export const TO_DESC_MODE = "TO_DESC_MODE"

export const AD_WORKER_START = 'AD_WORKER_START'
export const GET_AD_CONTENTS = 'GET_AD_CONTENTS'

export const PAGE_INCREMENT = 'PAGE_INCREMENT'