export const CONTENTS_WORKER_START = 'CONTENTS_WORKER_START'
export const GET_ASC_CONTENTS = "GET_ASC_CONTENTS"
export const GET_DESC_CONTENTS = "GET_ASC_CONTENTS"

export const AD_WORKER_START = 'AD_WORKER_START'
export const GET_AD_CONTENTS = 'GET_AD_CONTENTS'

export const PAGE_INCREMENT = 'PAGE_INCREMENT'