export const CONTENTS_WORKER_START = "CONTENTS_WORKER_START"
export const GET_ASC_CONTENTS = "GET_ASC_CONTENTS"
export const GET_DESC_CONTENTS = "GET_ASC_CONTENTS"

export const FILTER_CONTENT_WORKER_START = "FILTER_CONTENT_WORKER_START"
export const GET_FILTER_CONTENTS = "GET_FILTER_CONTENTS"

export const CATEGORY_WORKER_START = "CATEGORY_WORKER_START"
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_BEFORE_CATEGORY = "GET_BEFORE_CATEGORY"

export const NEXT_CONTENTS_WORKER_START = "NEXT_CONTENTS_WORKER_START"
export const ADD_NEXT_CONTENT = "ADD_NEXT_CONTENT"

export const TO_ASC_MODE = "TO_ASC_MODE"
export const TO_DESC_MODE = "TO_DESC_MODE"

export const AD_WORKER_START = "AD_WORKER_START"
export const GET_AD_CONTENTS = "GET_AD_CONTENTS"
export const GET_NEXT_AD = "GET_NEXT_AD"

export const PAGE_INCREMENT = "PAGE_INCREMENT"
export const RESET_PAGE = "RESET_PAGE"

export const FILTER_MODAL_OPEN = "FILTER_MODAL_OPEN"
export const FILTER_MODAL_CLOSE = "FILTER_MODAL_CLOSE"

export const CHANGE_TO_PICK = "CHANGE_TO_PICK"
export const CHANGE_TO_UNPICK = "CHANGE_TO_UNPICK"

export const PICKED_FILTER = "PICKED_FILTER"

export const VIEW_CONTENT_WORKER_START = "VIEW_CONTENT_WORKER_START"
export const GET_VIEW_CONTENT = "GET_VIEW_CONTENT"

export const LOADING_START = "LOADING_START"
export const LOADING_STOP = "LOADING_STOP"